final products = [
  // ===== Nike =====
  {
    'id': 'nike_1',
    'title': 'Nike Air Zoom',
    'price': 4200,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': 'nike_2',
    'title': 'Nike Revolution',
    'price': 3800,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Nike',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': 'nike_3',
    'title': 'Nike Pegasus',
    'price': 4500,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'nike_4',
    'title': 'Nike Downshifter',
    'price': 3600,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [9, 10, 11],
  },
  {
    'id': 'nike_5',
    'title': 'Nike Court Vision',
    'price': 4100,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'nike_6',
    'title': 'Nike Flex Run',
    'price': 3900,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Nike',
    'sizes': [7, 8, 9],
  },

  // ===== Addidas =====
  {
    'id': 'addidas_1',
    'title': 'Addidas Ultraboost',
    'price': 5000,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Addidas',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'addidas_2',
    'title': 'Addidas Run Falcon',
    'price': 3200,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Addidas',
    'sizes': [7, 8, 9],
  },
  {
    'id': 'addidas_3',
    'title': 'Addidas Lite Racer',
    'price': 3500,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Addidas',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'addidas_4',
    'title': 'Addidas Duramo',
    'price': 3000,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Addidas',
    'sizes': [9, 10],
  },
  {
    'id': 'addidas_5',
    'title': 'Addidas Galaxy',
    'price': 3400,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Addidas',
    'sizes': [8, 9],
  },
  {
    'id': 'addidas_6',
    'title': 'Addidas Advantage',
    'price': 3600,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Addidas',
    'sizes': [9, 10, 11],
  },

  // ===== Bata =====
  {
    'id': 'bata_1',
    'title': 'Bata Power Sneakers',
    'price': 2500,
    'imageUrl': 'assets/images/bata_shoes_1.png',
    'company': 'Bata',
    'sizes': [7, 8, 9],
  },
  {
    'id': 'bata_2',
    'title': 'Bata Red Label',
    'price': 2700,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'bata_3',
    'title': 'Bata Casual Shoes',
    'price': 2400,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Bata',
    'sizes': [7, 8],
  },
  {
    'id': 'bata_4',
    'title': 'Bata Formal Shoes',
    'price': 2600,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'bata_5',
    'title': 'Bata Sports Shoes',
    'price': 2900,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Bata',
    'sizes': [9, 10],
  },
  {
    'id': 'bata_6',
    'title': 'Bata Walking Shoes',
    'price': 2300,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Bata',
    'sizes': [7, 8, 9],
  },

  // ===== Red Tape =====
  {
    'id': 'redtape_1',
    'title': 'Red Tape Sports Shoes',
    'price': 3300,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Red Tape',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'redtape_2',
    'title': 'Red Tape Casual',
    'price': 3100,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Red Tape',
    'sizes': [7, 8, 9],
  },
  {
    'id': 'redtape_3',
    'title': 'Red Tape Running',
    'price': 3500,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Red Tape',
    'sizes': [8, 9],
  },
  {
    'id': 'redtape_4',
    'title': 'Red Tape Mesh',
    'price': 3400,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Red Tape',
    'sizes': [9, 10],
  },
  {
    'id': 'redtape_5',
    'title': 'Red Tape Comfort',
    'price': 3200,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Red Tape',
    'sizes': [8, 9],
  },
  {
    'id': 'redtape_6',
    'title': 'Red Tape Trainer',
    'price': 3600,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Red Tape',
    'sizes': [9, 10, 11],
  },

  // ===== Asics =====
  {
    'id': 'asics_1',
    'title': 'Asics Gel Venture',
    'price': 4800,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Asics',
    'sizes': [8, 9, 10],
  },
  {
    'id': 'asics_2',
    'title': 'Asics Nimbus',
    'price': 5200,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Asics',
    'sizes': [9, 10, 11],
  },
  {
    'id': 'asics_3',
    'title': 'Asics Patriot',
    'price': 4000,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Asics',
    'sizes': [8, 9],
  },
  {
    'id': 'asics_4',
    'title': 'Asics Contend',
    'price': 3900,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Asics',
    'sizes': [7, 8, 9],
  },
  {
    'id': 'asics_5',
    'title': 'Asics Trail',
    'price': 4500,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Asics',
    'sizes': [9, 10],
  },
  {
    'id': 'asics_6',
    'title': 'Asics Roadblast',
    'price': 4300,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Asics',
    'sizes': [8, 9, 10],
  },
];

